sonar.projectKey=UniEvent-Secure
sonar.projectName=UniEvent-Secure
sonar.projectVersion=1.0

sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_45ca3b05b2fffe186fc50f4fdf8ae1ad68e86b72

sonar.exclusions=node_modules/**